# Generated by Django 3.2.4 on 2021-06-28 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('_teacher', '0001_initial'),
        ('_stuff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_students', models.PositiveIntegerField()),
                ('total_sections', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LogisticsExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('receipt_no', models.CharField(blank=True, max_length=50, null=True)),
                ('model_no', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('total_students', models.PositiveIntegerField()),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.class')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/students')),
                ('age', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('_group', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.class')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.section')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=50)),
                ('total_chapter', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('total_students', models.PositiveIntegerField()),
                ('total_exams', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateField()),
                ('is_present', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.student')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=50)),
                ('salary_amount', models.PositiveIntegerField()),
                ('paying_date', models.DateTimeField(auto_now_add=True)),
                ('stuff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_stuff.stuff')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='_teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_mark', models.PositiveIntegerField()),
                ('objective_mark', models.PositiveIntegerField()),
                ('practical_mark', models.PositiveIntegerField()),
                ('total_mark', models.PositiveIntegerField()),
                ('is_passed', models.BooleanField()),
                ('publication_date', models.DateTimeField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.term')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField()),
                ('duration', models.FloatField()),
                ('_date', models.DateTimeField()),
                ('_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.class')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_school.term')),
            ],
        ),
    ]
