# Generated by Django 3.2.4 on 2021-06-28 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='term',
            name='year',
            field=models.CharField(default=2020, max_length=10),
            preserve_default=False,
        ),
    ]
