# Generated by Django 3.2.4 on 2021-06-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0002_term_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='grade',
            field=models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], default='F', max_length=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='_group',
            field=models.CharField(choices=[('None', 'None'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default='None', max_length=20),
        ),
    ]
