# Generated by Django 3.2.4 on 2021-06-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_school', '0003_auto_20210629_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='_class',
            field=models.CharField(choices=[('Six', 'Six'), ('Seven', 'Seven'), ('Eight', 'Eight')], default='None', max_length=20),
        ),
    ]
