# Generated by Django 3.2.4 on 2021-06-28 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/stuffs')),
                ('age', models.CharField(max_length=50)),
                ('stuff_id', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('stuff_salary', models.PositiveIntegerField()),
                ('is_active', models.BooleanField()),
                ('is_married', models.BooleanField()),
                ('phone', models.CharField(max_length=50)),
                ('blood_group', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StuffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_date', models.DateField()),
                ('is_present', models.BooleanField()),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_stuff.stuff')),
            ],
        ),
    ]
