# Generated by Django 3.2.4 on 2021-06-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='image',
            field=models.ImageField(upload_to='stuffs'),
        ),
    ]
